### ISSUE TITLE
session is clear when page is refreshed, why?

### ISSUE THREAD

**Issue by yuomtheara** [erasaur/server-session#2] opened 2015-01-20 02:57 UTC
When i refresh page the server session is cleared, why?
i don't want to clear.

**Comment by erasaur** [comment] 2015-01-20 08:05
By design, DDP connections are closed on page refresh. Since this package relies on the DDP SessionId for uniquely identifying clients, the session is cleared along with the DDP session. If you are looking for persistent sessions, consider looking at [Matteo's package](https://github.com/matteodem/meteor-server-session).

Cheers!

**Comment by yuomtheara** [comment] 2015-01-20 11:00
I try this package, but it have problem when the multi user login at the same time.

**Comment by JimiSpire** [comment] 2015-04-04 23:12
Weird, my case is the opposite; Even when i stop the current running meteor with ^C, when i start it back again, the sessions are still there and they eventually pile up and cause problems!

Could there be a command to clear all the unused sessions or an automation that clears them after an certain amount of time?

**Comment by erasaur** [comment] 2015-04-04 23:54
When you stop meteor with ^C, the package has no time to cleanup the sessions, so they will pile up. I've changed it so that all the sessions are cleared when you start up meteor, so hopefully that helps.

**Comment by erasaur** [comment] 2015-04-05 00:00
Closing this for now -- feel free to open another if you're still having issues.

**Closed by erasaur** 2015-04-05 00:00 UTC
